Automate repository and branch detection
Signed-off-by: Voplica <admin@voplica.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -19,12 +19,6 @@ branding:
   color: 'gray-dark'
 
 inputs:
-  repository:
-    description: 'Organization + Repository name. Format: `${org}/${repo}`.'
-    required: true
-  branch:
-    description: 'Branch name for which the cache cleanup is triggered.'
-    required: true
   dispatch_token:
     description: 'Token for workflow dispatch. Should be: `$GH_BUILDS_WORKFLOW_DISPATCH_TOKEN`'
     required: true
@@ -36,15 +30,37 @@ runs:
   using: "composite"
   steps:
 
+    # Step 1: Extract the branch name based on the event
+    - name: Extract branch name
+      id: extract_branch
+      shell: bash
+      run: |
+        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+          echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
+        elif [[ "${{ github.event_name }}" == "delete" ]]; then
+          echo "branch=${{ github.event.ref }}" >> $GITHUB_ENV
+        elif [[ "${{ github.event_name }}" == "repository_dispatch" && "${{ github.event.action }}" == "branch_archived" ]]; then
+          echo "branch=${{ github.event.client_payload.branch }}" >> $GITHUB_ENV
+        else
+          echo "Unknown event; exiting."
+          exit 1
+        fi
+
+    # Step 2: Debug information
+    - name: Debug Info
+      shell: bash
+      run: |
+        echo "Triggered by: ${{ github.event_name }}"
+        echo "Branch to clean: ${{ env.branch }}"
+
+    # Step 3: Trigger cache cleanup for a branch
     - name: Send workflow dispatch event
       shell: bash
       run: | 
-        
-        # Dispatch workflow to trigger build process
         curl -L \
           -X POST \
           -H 'Accept: application/vnd.github+json' \
           -H 'Authorization: Bearer ${{ inputs.dispatch_token }}' \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           '${{ inputs.dispatch_url }}' \
-          -d '{"ref":"main","inputs":{"repository":"${{ inputs.repository }}","branch":"${{ inputs.branch }}"}}'
+          -d '{"ref":"main","inputs":{"repository":"${{ github.repository }}","branch":"${{ env.branch }}"}}'
